---
collections:
  - name: community.general
    version: 6.3.0
  - name: kubernetes.core
    version: 2.3.2
#  - name: containers.podman
#    version: 1.10.1
  - name: devsec.hardening
    version: 8.6.0
  - name: redhat.rhel_system_roles
    version: 1.21.1
