---
all:
  children:
    molecule:
      hosts:
        vps-runtime:
          mp:
            kubevirt: "{{ molecule_guest_profiles.stream10 | combine(dict(memory='4Gi')) }}"
    vps:
      hosts:
        vps-runtime: {}
