---
all:
  children:
    molecule:
      hosts:
        molecule-smoke:
          mp:
            kubevirt:
              boot_source: "{{ molecule_boot_sources.stream10 }}"
              ssh_user: igou
              memory: 1Gi
