---
all:
  children:
    molecule:
      hosts:
        molecule-smoke:
          mp:
            kubevirt:
              boot_source:
                type: container_disk
                image: quay.io/containerdisks/centos-stream:10
              ssh_user: igou
              memory: 1Gi
