---
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Configure the haproxy cnf file with hosts
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0750
  notify: Restart haproxy

- name: Start the haproxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
