---
- hosts: sno
  name: Create ansible robot SA and save the credentials to 1password
  gather_facts: false
  tasks:
  - name: Create testing namespace exists
    kubernetes.core.k8s:
      kind: namespace
      name: nad-testing
      state: present

  - name: Ensure ssh auth secret exists
    kubernetes.core.k8s:
      resource_definition:
        apiVersion: v1
        stringData:
          key: "{{ lookup('community.general.onepassword', 'ansible-ssh', field='private key', vault='awx') }}"
        kind: Secret
        metadata:
          name: digouredhatcom
          namespace: nad-testing
        type: Opaque

  - name: Ensure NAD exists
    kubernetes.core.k8s:
      definition:
        apiVersion: k8s.cni.cncf.io/v1
        kind: NetworkAttachmentDefinition
        metadata:
          name: br1-network
          namespace: nad-testing
        spec:
          config: |
            {
              "cniVersion": "0.3.1",
              "name": "br1-network",
              "bridge": "br1",
              "type": "cnv-bridge"
            }

  - name: Ensure ubuntu-builder exists
    kubevirt.core.kubevirt_vm:
      name: ubuntu-builder
      state: present
      namespace: nad-testing
      labels:
        server: builder
      instancetype:
        kind: virtualmachineclusterinstancetype
        name: "u1.small"
      preference:
        kind: virtualmachineclusterpreference
        name: ubuntu
      data_volume_templates:
        - metadata:
            creationTimestamp: null
            name: ubuntu-builder-volume
          spec:
            sourceRef:
              kind: DataSource
              name: ubuntu-lts-24
              namespace: openshift-virtualization-os-images
            storage:
              resources: {}
              storageClassName: lvms-vg1-immediate
      spec:
        accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: digouredhatcom
        architecture: amd64
        domain:
          devices:
            interfaces:
            - bridge: {}
              model: virtio
              macAddress: 02:7a:1f:00:00:03
              name: ubuntu-builder-nic
            resources: {}
        networks:
        - multus:
            networkName: br1-network
          name: ubuntu-builder-nic
        subdomain: headless
        volumes:
        - dataVolume:
            name: ubuntu-builder-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              users:
                - name: igou
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  ssh-authorized-keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDumonWRoahxRVNYQT6dt76OkYyRThQ1e0Z/lAAMHcF4ffpZ138fZVWFHipT9f85EOqLkleqLWH6b3yj37+zOOCJ4lGoTSk0oFK92neiWLGV6ayTsvGojdV/cGrSefUP04FqleZirSiwv52FYEVA21vPNweaB70L3m4i7x7+VaHqVvtPh4qT0LnnWa2Yf6Oq6aQU0WUi7Sd388SVczcWVZlJ9L+iibjtir1sm0NUE4Z+sEwHYCOfO2m6YbN809z2GQz1q+DchM0cJhpwBmwH+MIv3wjahM4Khz+XNz4bjousak63BMnZwqROf4jkoQoMrvy3Q/4WZHvivkLTu/Bj51p7TtFPTN1XNHq4kt5qzLE63HsQyhOy9lGdZpLk8cigZe14aQ1NV5WbXm0YSgPIdXTNgpHtXxzUGHjioqEhoMx4q/YBbIHZAFrX8eYorE0nhSzE63HA4cJsjMS56zAs3gk6SaG2Vux04+NwhAOftbQpF8wzwbS0QzdPzw42XKHMVDmQEW/YtPw8XVC15mmHTu6QEYjzBBYU6Noi37PXWOrad2wkq5bInIdlH6VBRuOQ0tw+9VeUlnYUoS9fD8lxcsuGiN3iVaLH8R4kptirEnr0VUBblo3fe1M3YqNiuqXpcB4HJ7sEaKIcyqEetGFRYFmbnvj4iM9BJ5uDb3pgzzmYw== digou@redhat.com
          name: cloudinitdisk
