---
- name: Set the state of an Kubevirt VM
  hosts: sno
  gather_facts: false
  vars:
    create_namespace: false
    set_stat: true
    vm_state: "absent"
    vm_labels:
      created_by: "ansible"
    vm_name: kubevirt-manage-testing
    vm_instancetype: "u1.small"
    vm_namespace: "default"
    vm_os_image_datasource: rhel9

    vm_services:
    - name: service-1
      type: ClusterIP
      clusterIP: None
      ports:
        - target_port: 9090
    - name: service-2
      type: NodePort
      ports:
        - target_port: 9090

    vm_routes:
      - name: route-1
        service_name: service-1
        hostname: cockpit-test.apps.sno.igou.systems
        tls:
          insecureEdgeTerminationPolicy: Redirect
          termination: passthrough
  roles:
    - ansible-role-kubevirt_vm_manage
  tasks:

    - name: Set stat for vm name
      ansible.builtin.set_stats:
        data:
          host: "{{ vm_namespace }}-{{ vm_name }}"
        per_host: false
      when: set_stat is true



    # - name: Wait for VMI to have an IP address todo: Make this more flexible
    #   kubevirt.core.kubevirt_vmi_info:
    #     name: "{{ vm_name }}"
    #     namespace: "{{ vm_namespace }}"
    #   register: vmi_info
    #   until: vmi_info.resources[0].status.interfaces[0].ipAddress is defined
    #   retries: 30
    #   delay: 10
    #   ignore_errors: yes
    #   when: check_for_ip is true