---
- name: Set the state of an Kubevirt VM
  hosts: sno
  gather_facts: false
  vars:
    create_namespace: false
    set_stat: true
    vm_state: "absent"
    vm_labels:
      created_by: "ansible"
    vm_name: kubevirt-manage-testing
    vm_instancetype: "u1.small"
    vm_namespace: "default"
    vm_os_image_datasource: rhel9
  roles:
    - David-Igou.kubevirt_vm_manage
  tasks:

    - name: Set stat for vm name
      ansible.builtin.set_stats:
        data:
          host: "{{ vm_namespace }}-{{ vm_name }}"
        per_host: false
      when: set_stat is true



    # - name: Wait for VMI to have an IP address todo: Make this more flexible
    #   kubevirt.core.kubevirt_vmi_info:
    #     name: "{{ vm_name }}"
    #     namespace: "{{ vm_namespace }}"
    #   register: vmi_info
    #   until: vmi_info.resources[0].status.interfaces[0].ipAddress is defined
    #   retries: 30
    #   delay: 10
    #   ignore_errors: yes
    #   when: check_for_ip is true