---
all:
  children:
    devenv:
      hosts:
        devenv-devenv: {}
    armbian_builders:
      hosts:
        devenv-devenv: {}
    molecule:
      hosts:
        devenv-devenv:
          mp:
            kubevirt:
              boot_source:
                type: data_volume_source_ref
                source_ref:
                  name: centos-stream10
                  namespace: openshift-virtualization-os-images
                size: 30Gi
              ssh_user: igou
              cpu:
                cores: 4
              memory: 8Gi
              extra_disks:
                - name: docker-scratch
                  serial: docker
                  disk:
                    bus: virtio
              extra_volumes:
                - name: docker-scratch
                  emptyDisk:
                    capacity: 20Gi
              application_ports:
                - name: code-server
                  port: 8080
