---
all:
  children:
    devenv:
      hosts:
        devenv-devenv: {}
    armbian_builders:
      hosts:
        devenv-devenv: {}
    molecule:
      hosts:
        devenv-devenv:
          mp:
            kubevirt:
              boot_source: "{{ molecule_boot_sources.stream10 }}"
              ssh_user: igou
              cpu:
                cores: 4
              memory: 8Gi
              extra_disks:
                - name: docker-scratch
                  serial: docker
                  disk:
                    bus: virtio
              extra_volumes:
                - name: docker-scratch
                  emptyDisk:
                    capacity: 20Gi
              application_ports:
                - name: code-server
                  port: 8080
