---
- name: Install required packages
  ansible.builtin.package:
    name:
      - mdadm
    state: present

- name: Prepare device paths
  set_fact:
    device_paths: "{{ raid_devices | map('regex_replace', '^UUID=([a-fA-F0-9-]+)$', '/dev/disk/by-uuid/\\1') | list }}"

- name: Get RAID array information
  ansible.builtin.command:
    cmd: "mdadm --detail /dev/{{ raid_name | default('md0') }}"
  register: raid_info
  changed_when: false
  failed_when: false

- name: Check if RAID array exists and matches the desired configuration
  set_fact:
    raid_needs_update: >
      raid_info.rc != 0 or
      raid_level not in raid_info.stdout or
      (device_paths | difference(raid_info.stdout_lines | regex_findall('/dev/\\S+', multiline=True))) | length > 0
  tags: always

- name: Stop existing RAID array (if wipe is true and RAID needs update)
  ansible.builtin.command:
    cmd: "mdadm --stop /dev/{{ raid_name | default('md0') }}"
  register: stop_raid
  failed_when: "stop_raid.rc != 0 and 'no such file or directory' not in stop_raid.stderr|lower"
  when: wipe | default(false) and raid_needs_update

- name: Zero superblock on devices (if RAID needs update)
  ansible.builtin.command:
    cmd: "mdadm --zero-superblock {{ item }}"
  loop: "{{ device_paths }}"
  when: raid_needs_update and stop_raid is changed

- name: Wipe filesystem signatures (if wipe is true)
  ansible.builtin.command:
    cmd: "wipefs -a {{ item }}"
  loop: "{{ device_paths }}"
  when: wipe | default(false) and raid_needs_update and stop_raid is changed

- name: Create RAID array (if RAID needs update)
  ansible.builtin.command:
    cmd: "mdadm --create /dev/{{ raid_name | default('md0') }} --level={{ raid_level }} --raid-devices={{ device_paths | length }} {{ device_paths | join(' ') }}"
  when: raid_needs_update and stop_raid is changed

- name: Get RAID array information (after changes)
  ansible.builtin.command:
    cmd: "mdadm --detail /dev/{{ raid_name | default('md0') }}"
  register: raid_info_after_changes
  changed_when: false
  failed_when: false

- name: Display RAID array details
  ansible.builtin.debug:
    var: raid_info_after_changes.stdout_lines
