---
- name: Install required packages
  package:
    name:
      - mdadm
      - parted
    state: present

- name: Stop existing RAID array
  community.general.mdadm:
    name: /dev/md0
    state: stopped
  ignore_errors: yes
  when: rebuild_raid_array | default(false) | bool

- name: Zero devices and remove RAID superblock
  command: "mdadm --zero-superblock {{ item }}"
  loop: "{{ raid_devices }}"
  when: rebuild_raid_array | default(false) | bool

- name: Create partitions for RAID devices
  parted:
    device: "{{ item }}"
    number: 1
    state: present
    label: gpt
    part_start: 0%
    part_end: 100%
    part_type: primary
  loop: "{{ raid_devices }}"

- name: Create the RAID10 array
  community.general.mdadm:
    name: /dev/md0
    level: 10
    raid_devices: "{{ raid_device_partitions }}"
    state: present
