---
- name: Install required packages
  package:
    name:
      - mdadm
      - parted
    state: present

- name: Stop existing RAID array
  community.general.mdadm:
    name: /dev/md0
    state: stopped
  ignore_errors: yes
  when: rebuild_raid_array | default(false) | bool

- name: Zero devices and remove RAID superblock
  command: "mdadm --zero-superblock {{ item }}"
  loop: "{{ raid_devices }}"
  when: rebuild_raid_array | default(false) | bool

- name: Create partitions for RAID devices
  parted:
    device: "{{ item }}"
    number: 1
    state: present
    label: gpt
    part_start: 0%
    part_end: 100%
    part_type: primary
  loop: "{{ raid_devices }}"

- name: Create the RAID10 array
  community.general.mdadm:
    name: /dev/md0
    level: 10
    raid_devices: "{{ raid_device_partitions }}"
    state: present

- name: Create filesystem on the RAID array
  ansible.builtin.filesystem:
    dev: /dev/md0
    fstype: ext4
    force: "{{ rebuild_raid_array | default(false) | bool }}"

- name: Create a mount point for the RAID array
  ansible.builtin.file:
    path: "{{ mount_point }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Mount the RAID array
  ansible.builtin.mount:
    path: "{{ mount_point }}"
    src: /dev/md0
    fstype: ext4
    opts: defaults
    state: mounted
