- name: Install required packages
  ansible.builtin.package:
    name:
      - mdadm
      - parted
    state: present

- block:
    - name: Remove any existing partitions on devices
      ansible.builtin.parted:
        device: "{{ item }}"
        state: absent
      loop: "{{ raid_devices }}"

    - name: Wipe filesystem metadata from devices
      ansible.builtin.command:
        cmd: "wipefs --all --force {{ item }}"
      loop: "{{ raid_devices }}"

    - name: Create partitions on devices
      ansible.builtin.parted:
        device: "{{ item }}"
        number: 1
        state: present
      loop: "{{ raid_devices }}"

    - name: Rebuild RAID array
      ansible.builtin.mdadm:
        name: /dev/md0
        level: "{{ raid_level }}"
        devices: "{{ raid_device_partitions }}"
        state: present
  when: wipe | default(false)

- name: Verify RAID array is present
  ansible.builtin.mdadm:
    name: /dev/md0
    level: "{{ raid_level }}"
    devices: "{{ raid_device_partitions }}"
    state: present
  when: not (wipe | default(false))
