---
all:
  children:
    molecule:
      hosts:
        winclient:
          molecule_windows_admin_mode: local_account
          mp:
            kubevirt:
              boot_source:
                type: data_volume_pvc
                source:
                  name: win11
                  namespace: openshift-virtualization-os-images
                size: 50Gi
              preference: windows.11
              admin_user: moleculeadmin
              sysprep_secret: "{{ inventory_hostname }}-sysprep-{{ molecule_consumer_run_id }}"
              application_ports:
                - name: iis
                  port: 8080
                - name: rdp
                  port: 3389
                - name: allowed
                  port: 7777
                - name: blocked
                  port: 7778
        winserver:
          molecule_windows_admin_mode: builtin
          mp:
            kubevirt:
              boot_source:
                type: data_volume_pvc
                source:
                  name: win2k25
                  namespace: openshift-virtualization-os-images
                size: 50Gi
              preference: windows.2k25
              admin_user: Administrator
              sysprep_secret: "{{ inventory_hostname }}-sysprep-{{ molecule_consumer_run_id }}"
              application_ports:
                - name: iis
                  port: 8080
                - name: rdp
                  port: 3389
                - name: allowed
                  port: 7777
                - name: blocked
                  port: 7778
    windows:
      hosts:
        winclient: {}
        winserver: {}
    windows_guests:
      hosts:
        winclient: {}
        winserver: {}
    windows_client:
      hosts:
        winclient: {}
    windows_server:
      hosts:
        winserver: {}
