---
# This EE intentionally has legacy security policies to communicate with legacy devices.
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
    - name: community.general
      version: 10.2.0
    - name: ansible.netcommon
      version: 7.1.0
    - name: community.network
      version: 5.1.0
    - name: vyos.vyos
      version: 5.0.0
    - name: arista.eos
      version: 10.0.1
  system: |
    python3.11-devel [platform:rpm compile]
    libcurl-devel [platform:rpm compile]
    krb5-devel [platform:rpm compile]
    krb5-workstation [platform:rpm]
    subversion [platform:rpm]
    subversion [platform:dpkg]
    git-lfs [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    epel-release [platform:rpm]
    unzip [platform:rpm]
    podman-remote [platform:rpm]
    cmake [platform:rpm compile]
    gcc [platform:rpm compile]
    gcc-c++ [platform:rpm compile]
    make [platform:rpm compile]
    openssl-devel [platform:rpm compile]
    1password-cli
    crypto-policies-scripts [platform:rpm]
    tar
  python: |
    awxkit
    git+https://github.com/ansible/ansible-sign
    ncclient
    paramiko
    pykerberos
    pyOpenSSL
    pypsrp[kerberos,credssp]
    pywinrm[kerberos,credssp]
    toml
    pexpect>=4.5
    python-daemon
    pyyaml
    six
    receptorctl
additional_build_files:
  - dest: configs
    src: custom.conf
additional_build_steps:
  prepend_base: |
    RUN microdnf install -y git-core
  append_base: |
    RUN $PYCMD -m pip install -U pip

    RUN echo "Target architecture is: $TARGETARCH"

    RUN rpm --import https://downloads.1password.com/linux/keys/1password.asc && \
    sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'

  append_final: |
    COPY _build/configs/custom.conf /etc/ssh/ssh_config.d/custom.conf
    RUN chmod 600 /etc/ssh/ssh_config.d/custom.conf
    RUN rm /etc/ssh/ssh_config.d/50-redhat.conf
    COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    RUN mkdir -p /var/run/receptor
    RUN git lfs install --system
    # SymLink `python` -> `python3.11`
    RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311
    # Output collections list for debugging
    RUN update-crypto-policies --set LEGACY
    RUN update-crypto-policies --set DEFAULT:SHA1
    RUN ansible-galaxy collection list