---
roles:
  - name: xanmanning.k3s
    version: v3.6.2
  - name: linux-system-roles.podman
    version: 1.11.1
  - name: githubixx.iscsi_target
    version: 2.0.0
  - name: githubixx.ansible_role_wireguard
    version: 19.1.0
  - name: robertdebock.kubectl
    version: 2.1.5
  - name: robertdebock.update
    version: 3.1.10
  - name: robertdebock.terraform
    version: 4.1.9
  - name: geerlingguy.helm
    version: 1.0.1
  - name: David-Igou.kubevirt_vm_manage
    version: 0.0.3
  - name: David-Igou.haproxy
    version: 1.0.0
  - name: david-igou.openshift_agent_install
    version: "0.1"
  - name: geerlingguy.kubernetes
    version: 8.2.0
  - name: geerlingguy.containerd
    version: 1.4.1
collections:
  - name: community.general
    version: 13.0.1
  - name: ansible.posix
    version: 2.2.0
  - name: kubernetes.core
    version: 6.4.0
  - name: containers.podman
    version: 1.20.2
  - name: devsec.hardening
    version: 10.6.0
  - name: kubevirt.core
    version: 2.2.4
  - name: ansible.utils
    version: 6.0.2
  - name: felixfontein.acme
    version: 0.11.0
  - name: community.crypto
    version: 3.2.1
  - name: artis3n.tailscale
    version: 1.2.1
  - name: https://github.com/david-igou/ansible-truenas.git
    type: git
    version: fix-user-update
  - name: community.docker
    version: 5.2.1
  - name: vkhitrin.libguestfs
    version: 1.1.5
  - name: ansible.netcommon
    version: 8.5.2
  - name: community.routeros
    version: 3.20.0
  - name: david_igou.routeros_configuration
    version: 0.0.7-alpha
  - name: amazon.aws
    version: 11.3.0
  - name: prometheus.prometheus
    version: 0.30.0
  - name: https://github.com/david-igou/ansible-collection-armbian.git
    type: git
    version: v0.0.4-alpha
...
