---
roles:
  - name: xanmanning.k3s
    version: v3.6.2
  - name: githubixx.iscsi_target
    version: 2.0.0
  - name: githubixx.ansible_role_wireguard
    version: 18.3.0
  - name: robertdebock.kubectl
    version: 2.1.5
  - name: robertdebock.update
    version: 3.1.10
  - name: robertdebock.terraform
    version: 4.1.9
  - name: geerlingguy.helm
    version: 1.0.1
  - name: ansible-zfs
    version: master
    scm: git
    src: https://github.com/mrlesmithjr/ansible-zfs.git
  - name: David-Igou.single_node_openshift_iso
    version: main
    scm: git
    src: https://github.com/David-Igou/ansible-role-single_node_openshift_iso.git
  - name: David-Igou.kubevirt_vm_manage
    version: 0.0.3
  - name: geerlingguy.postgresql
  - name: davidwittman.redis
    src: https://github.com/DavidWittman/ansible-redis.git
    version: 1.2.12
  - name: lae.netbox
    src: https://github.com/lae/ansible-role-netbox.git
    version: v1.0.7
  - name: David-Igou.haproxy
    version: 1.0.0
collections:
  - name: geerlingguy.kubernetes
    version: 8.2.0
  - name: community.general
    version: 12.2.0
  - name: ansible.posix
    version: 2.1.0
  - name: kubernetes.core
    version: 6.2.0
  - name: containers.podman
    version: 1.18.0
  - name: devsec.hardening
    version: 10.4.0
  - name: kubevirt.core
    version: 2.2.3
  - name: ansible.utils
    version: 6.0.0
  - name: https://github.com/David-Igou/ee_utilities.git
    version: devel
    type: git
  - name: vkhitrin.libguestfs
    version: 1.1.5
  - name: awx.awx
  - name: azure.azcollection
    version: ">=2.1.0"
  - name: amazon.aws
  - name: theforeman.foreman
  - name: kubernetes.core
  - name: ansible.windows
  - name: ansible.netcommon
  - name: community.network
  - name: junipernetworks.junos
  - name: felixfontein.acme
    version: 0.11.0
  - name: artis3n.tailscale
    version: 1.2.0