---
roles:
  - name: xanmanning.k3s
    version: v3.4.2
  - name: githubixx.iscsi_target
    version: 1.2.0
  - name: githubixx.ansible_role_wireguard
    version: 15.0.0
  - name: robertdebock.kubectl
    version: 2.1.5
  - name: robertdebock.update
    version: 3.1.7
  - name: robertdebock.terraform
    version: 4.1.7
  - name: geerlingguy.helm
    version: 1.0.1
collections:
  - name: infra.controller_configuration
    version: 2.7.1
  - name: community.general
    version: 8.6.0
  - name: kubernetes.core
    version: 3.0.0
  - name: containers.podman
    version: 1.11.0
  - name: devsec.hardening
    version: 9.0.0
