---
roles:
  - name: xanmanning.k3s
    version: v3.4.4
  - name: githubixx.iscsi_target
    version: 2.0.0
  - name: githubixx.ansible_role_wireguard
    version: 17.0.0
  - name: robertdebock.kubectl
    version: 2.1.5
  - name: robertdebock.update
    version: 3.1.8
  - name: robertdebock.terraform
    version: 4.1.8
  - name: geerlingguy.helm
    version: 1.0.1
  - name: ansible-zfs
    version: master
    scm: git
    src: https://github.com/mrlesmithjr/ansible-zfs.git
  - name: davidigou.single_node_ocp_iso
    version: main
    scm: git
    src: https://github.com/David-Igou/ansible-role-single_node_ocp_iso.git
collections:
  - name: infra.controller_configuration
    version: 2.9.0
  - name: community.general
    version: 8.6.3
  - name: ansible.posix
    version: 1.5.4
  - name: kubernetes.core
    version: 5.0.0
  - name: containers.podman
    version: 1.15.4
  - name: devsec.hardening
    version: 9.0.1
  - name: kubevirt.core
    version: 2.0.0