---
roles:
  - name: xanmanning.k3s
    version: v3.4.4
  - name: githubixx.iscsi_target
    version: 2.0.0
  - name: githubixx.ansible_role_wireguard
    version: 17.0.0
  - name: robertdebock.kubectl
    version: 2.1.5
  - name: robertdebock.update
    version: 3.1.9
  - name: robertdebock.terraform
    version: 4.1.8
  - name: geerlingguy.helm
    version: 1.0.1
  - name: artis3n.tailscale
    version: v4.5.0
  - name: ansible-zfs
    version: master
    scm: git
    src: https://github.com/mrlesmithjr/ansible-zfs.git
  - name: David-Igou.single_node_openshift_iso
    version: main
    scm: git
    src: https://github.com/David-Igou/ansible-role-single_node_openshift_iso.git
collections:
  - name: infra.controller_configuration
    version: 2.11.0
  - name: community.general
    version: 9.5.0
  - name: ansible.posix
    version: 1.6.2
  - name: kubernetes.core
    version: 5.0.0
  - name: containers.podman
    version: 1.16.1
  - name: devsec.hardening
    version: 10.0.0
  - name: kubevirt.core
    version: 2.1.0
  - name: ansible.utils
    version: 5.1.2
  - name: https://github.com/redhat-cop/infra.osbuild.git
    version: main
    type: git
  - name: https://github.com/David-Igou/ee_utilities.git
    version: devel
    type: git
  - name: vkhitrin.libguestfs
    version: 1.1.5
