---
prerun: false
ansible:
  cfg:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles:${MOLECULE_PROJECT_DIRECTORY}/.ansible/roles
      collections_path: ${MOLECULE_PROJECT_DIRECTORY}/.ansible/collections
  playbooks:
    converge: converge.yml
    verify: verify.yml
scenario:
  name: logic-codex-desktop
  test_sequence:
    - syntax
    - converge
    - verify
verifier:
  name: ansible
