---
- hosts: localhost
  gather_facts: false
  tasks:

  - name: Retrieve password for KITT when already signed in to 1Password
    ansible.builtin.debug:
      var: lookup('community.general.onepassword', 'FOO', field='password', vault='awx')
