---
- hosts: "{{ host }}"
  name: Simple test to read objects from k8s API
  gather_facts: false
  tasks:
    - name: Set Up Directory
      block:
        - name: Create a temporary directory
          ansible.builtin.tempfile:
            state: directory
          register: temp_dir

        - name: Get kubeconfig
          ansible.builtin.copy:
            content: "{{ kubeconfig }}"
            mode: 0644
            dest: "{{ temp_dir.path }}/kubeconfig"
          no_log: false

    - name: kubectl commands
      environment:
        K8S_AUTH_KUBECONFIG: "{{ temp_dir.path }}/kubeconfig"
      block:

        - name: Check for presence of awx-web Deployment
          k8s_info:
            api_version: v1
            kind: Deployment
            name: "awx-web"
            namespace: "awx"
          register: awx_web_deployment

        - name: check value
          ansible.builtin.debug:
            var: awx_web_deployment