---
scenario:
  name: alloy-logging
  test_sequence:
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
ansible:
  playbooks:
    prepare: prepare.yml
