---
- name: Playbook to configure execution environments
  hosts: aap-rhel-builder
  gather_facts: true
  vars:
    ee_builder_dir: "{{ temp_dir.path }}/execution-environments/{{ ee_list[0].name }}"
    ee_update_base_images: true
    ee_base_registry_username: "{{ lookup('community.general.onepassword', 'redhat-registry', field='username', vault='awx') }}"
    ee_base_registry_password: "{{ lookup('community.general.onepassword', 'redhat-registry', field='password', vault='awx') }}"
    ee_pull_collections_from_hub: false
    ee_registry_dest: quay.io/igou
    ee_registry_username: "{{ lookup('community.general.onepassword', 'quay', field='username', vault='awx') }}"
    ee_registry_password: "{{ lookup('community.general.onepassword', 'quay', field='password', vault='awx') }}"
    ee_verbosity: 3
    ee_list:
      - name: igou-aap-ee-rhel9
        alt_name: Suported EE
        tag: "latest"
        skip_generation: true
  pre_tasks:
    - name: Validate that ansible-builder is installed on target system
      block:
        - name: Try command
          ansible.builtin.command: ansible-builder --version
          register: r_builder
          changed_when: false
      rescue:
        - name: Try to install with rpms
          block:
            - name: Install ansible-builder from rpm
              ansible.builtin.dnf:
                name:
                  - ansible-builder
                  - ansible-core
                enablerepo: ansible-automation-platform-2.5-for-rhel-9-x86_64-rpms
                state: present
              become: true
          rescue:
            - name: Install ansible-builder from pip # noqa package-latest
              ansible.builtin.pip:
                name:
                  - ansible-builder
                  - ansible-core
                state: latest

  tasks:
    - name: Set Up Directory
      block:
        - name: Create a temporary directory
          ansible.builtin.tempfile:
            state: directory
          register: temp_dir

        - name: Clone a repo with separate git directory
          ansible.builtin.git:
            repo: https://github.com/igou-io/igou-ansible.git
            dest: "{{ temp_dir.path }}"
            clone: true

        - name: Create ansible.cfg
          ansible.builtin.copy:
            content: "{{ lookup('community.general.onepassword', 'aap_ansiblecfg', field='file', vault='awx') }}"
            mode: 0644
            dest: "{{ temp_dir.path }}/execution-environments/{{ ee_list[0].name }}/ansible.cfg"
          no_log: false

        - name: Hack around collection expecting execution_environment.yml
          ansible.builtin.copy:
            src: "{{ temp_dir.path }}/execution-environments/{{ ee_list[0].name }}/execution-environment.yml"
            dest: "{{ temp_dir.path }}/execution-environments/{{ ee_list[0].name }}/execution_environment.yml"


    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
...