---
- name: Sync credentials
  hosts: aap
  gather_facts: false
  tasks:

    - name: Configure AAP Credentials
      ansible.builtin.include_role:
        name: infra.aap_configuration.controller_credentials
      vars:
        assign_galaxy_credentials_to_org: false
        assign_default_ee_to_org: false