---
- name: Playbook to configure ansible controller post installation
  hosts: "{{ host }}"
  gather_facts: false
  become: false
  vars:
    ansible_ssh_common_args: "-A"
    aap_setup_containerized: true
    aap_setup_down_dest_dir: /tmp
    aap_setup_down_offline_token: "{{ lookup('community.general.onepassword', 'rhsm-api', field='password', vault='awx') }}"
    aap_setup_working_dir: /tmp
    aap_setup_prep_working_dir: /tmp/workingdir
    aap_setup_prep_process_template: true

  tasks:
    - name: Download AAP bundle
      ansible.builtin.include_role:
        name: infra.aap_utilities.aap_setup_download

    - name: Set up AAP bundle
      ansible.builtin.include_role:
        name: infra.aap_utilities.aap_setup_prepare

    - name: Install up AAP bundle
      ansible.builtin.include_role:
        name: infra.aap_utilities.aap_setup_install
