---
- name: Test connection to RouterOS devices
  hosts: "{{ host | default('routeros') }}"
  gather_facts: false
  tasks:
    - name: Fetch system identity and resource info
      community.routeros.command:
        commands:
          - /system identity print
          - /system resource print
      register: routeros_info

    - name: Show output
      ansible.builtin.debug:
        var: routeros_info.stdout_lines
