---
- name: Deploy Kubevirt VM
  hosts: localhost
  gather_facts: false
  roles:
    - kubevirt_vm_launch

  tasks:
    - name: set host stat
      ansible.builtin.set_stats:
        data:
          host: "{{ vm_namespace }}-{{ vm_name }}"
        per_host: false

    - name: sleep 20 seconds so inventory can catch up
      ansible.builtin.pause:
        seconds: 20