- name: Configure LVM with multiple volume groups, logical volumes, and thin pools
  hosts: "{{ hosts }}"
  become: yes
  roles:
    - lvm
    - githubixx.iscsi_target
  tasks:
  - name: Run script to set generate_node_acls for all iSCSI targets and save the configuration
    ansible.builtin.shell: |
      for iqn in $(targetcli ls /iscsi | grep iqn | awk '{print $2}'); do
          targetcli /iscsi/${iqn}/tpg1/ set attribute generate_node_acls=1
      done
      targetcli saveconfig
