---
- name: Set the state of an Kubevirt VM
  hosts: sno
  gather_facts: false
  vars:
    vm_state: "absent"
    vm_labels:
      created_by: "ansible"
    vm_name: kubevirt-manage-testing
    vm_instancetype: "u1.small"
    vm_namespace: "default"
    vm_user_data:  |
      #cloud-config
      chpasswd:
        expire: false
      user: igou
      password: "changeme"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDumonWRoahxRVNYQT6dt76OkYyRThQ1e0Z/lAAMHcF4ffpZ138fZVWFHipT9f85EOqLkleqLWH6b3yj37+zOOCJ4lGoTSk0oFK92neiWLGV6ayTsvGojdV/cGrSefUP04FqleZirSiwv52FYEVA21vPNweaB70L3m4i7x7+VaHqVvtPh4qT0LnnWa2Yf6Oq6aQU0WUi7Sd388SVczcWVZlJ9L+iibjtir1sm0NUE4Z+sEwHYCOfO2m6YbN809z2GQz1q+DchM0cJhpwBmwH+MIv3wjahM4Khz+XNz4bjousak63BMnZwqROf4jkoQoMrvy3Q/4WZHvivkLTu/Bj51p7TtFPTN1XNHq4kt5qzLE63HsQyhOy9lGdZpLk8cigZe14aQ1NV5WbXm0YSgPIdXTNgpHtXxzUGHjioqEhoMx4q/YBbIHZAFrX8eYorE0nhSzE63HA4cJsjMS56zAs3gk6SaG2Vux04+NwhAOftbQpF8wzwbS0QzdPzw42XKHMVDmQEW/YtPw8XVC15mmHTu6QEYjzBBYU6Noi37PXWOrad2wkq5bInIdlH6VBRuOQ0tw+9VeUlnYUoS9fD8lxcsuGiN3iVaLH8R4kptirEnr0VUBblo3fe1M3YqNiuqXpcB4HJ7sEaKIcyqEetGFRYFmbnvj4iM9BJ5uDb3pgzzmYw== digou@redhat.com
      runcmd:
        - [ systemctl, enable, --now, cockpit.socket ]
    vm_virtualmachineclusterpreference: "fedora"
    vm_data_volume:
      sourceRef:
        name: fedora
    vm_services:
      - name: fedora-cockpit
        type: ClusterIP
        clusterIP: None
        ports:
          - target_port: 9090
      - name: fedora-ssh-nodeport
        type: NodePort
        ports:
          - target_port: 22
    vm_routes:
      - name: fedora-cockpit
        service_name: fedora-cockpit
        tls:
          insecureEdgeTerminationPolicy: Redirect
          termination: passthrough
  roles:
    - ansible-role-kubevirt_vm_manage
