---
# Openshift-based testing template (CRC)
# CRC is quite rigid in configuration so many of these parameters are not configurable and thus there aren't default assertions for environment varibales
driver:
  name: default
  delete: true # Run crc delete first
  cleanup: true # Run crc cleanup before start
  # crc setup configures the host machine to run crc (ie, /etc/hosts entries)
  setup: true # run crc setup before start
platforms:
  - name: okd # All crc clusters are named crc, this variable is not referenced in execution
    config:
      bundle: docker://quay.io/crcont/okd-bundle:4.19.0-okd-scos.19
      preset: okd
      consent-telemetry: no

provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        kubeconfig: "${KUBECONFIG:-$HOME/.crc/machines/crc/kubeconfig}"
        cluster_name: "${MOLECULE_K8S_CLUSTER:crc}"
  env:
    KUBECONFIG: "${KUBECONFIG:-$HOME/.crc/machines/crc/kubeconfig}"
    K8S_AUTH_KUBECONFIG: "${KUBECONFIG:-$HOME/.crc/machines/crc/kubeconfig}"
    K8S_AUTH_VERIFY_SSL: "${K8S_AUTH_VERIFY_SSL:-true}"

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  destroy_sequence:
    - destroy
