---
all:
  children:
    molecule:
      hosts:
        logging-centos:
          mp:
            kubevirt: "{{ molecule_guest_profiles.stream10 }}"
    linux_logging:
      hosts:
        logging-centos: {}
