---
all:
  children:
    molecule:
      hosts:
        windc01:
          mp:
            kubevirt:
              boot_source: "{{ molecule_boot_sources.win2k25 }}"
              preference: windows.2k25
              admin_user: Administrator
              sysprep_secret: "{{ inventory_hostname }}-sysprep-{{ molecule_consumer_run_id }}"
              namespace: molecule
        winmem01:
          mp:
            kubevirt:
              boot_source: "{{ molecule_boot_sources.win2k25 }}"
              instancetype: u1.medium
              preference: windows.2k25
              admin_user: Administrator
              sysprep_secret: "{{ inventory_hostname }}-sysprep-{{ molecule_consumer_run_id }}"
              namespace: molecule
    windows:
      hosts:
        winmem01: {}
    windows_guests:
      hosts:
        windc01: {}
        winmem01: {}
