---
all:
  children:
    molecule:
      hosts:
        kiosk-cog:
          kiosk_stack: cog
          mp:
            kubevirt:
              boot_source:
                type: container_disk
                image: quay.io/containerdisks/debian:13
              vm_overrides:
                spec:
                  template:
                    spec:
                      domain:
                        devices:
                          video:
                            type: virtio
        kiosk-chromium:
          kiosk_stack: chromium
          mp:
            kubevirt: {}
    grafana_kiosk:
      hosts:
        kiosk-cog: null
        kiosk-chromium: null
