---
- hosts: loadbalancer
  name: Configure HAProxy Loadbalancer for external k8s cluster
  become: true
  roles:
    - role: artis3n.tailscale
      vars:
        verbose: true
        tailscale_authkey: "{{ lookup('community.general.onepassword', 'tailscale-authkey', field='password', vault='awx') }}"
        tailscale_tags:
          - loadbalancer
    - role: haproxy
      frontends:
        - default_backend: https
          mode: tcp
          name: https
          options:
            - tcplog
          port: 443
      backends:
        - balance: source
          hosts:
            - ingress-ingress-ingress-nginx-controller
          mode: tcp
          name: https
          port: 443
