---
- hosts: loadbalancer
  name: Configure HAProxy Loadbalancer for external k8s cluster
  become: true
  roles:
    - role: artis3n.tailscale
      vars:
        verbose: true
        tailscale_authkey: "{{ lookup('community.general.onepassword', 'tailscale-loadbalancer-authkey', field='password', vault='awx') }}"
        tailscale_tags:
          - loadbalancer
    - role: haproxy
