---
- hosts: "{{ host }}"
  name: Configure HAProxy Loadbalancer for k8s ingress traffic and api
  become: true
  roles:
    - role: haproxy
      ingress_hosts: "{{ ingress_ips }}"
      masters: "{{ master_ips }}"
