---
- hosts: private_cluster_ingress
  name: Hack around no ddns, add master to ingress nodes /etc/hosts
  become: true
  tasks:
    - name: Add master to /etc/hosts of ingress node
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "10.10.1.10 master.igou.io"

- hosts: k8s_external
  name: Install k3s cluster
  become: true
  vars:
    k3s_registration_address: master.igou.io  # Typically a load balancer.
  roles:
    - role: xanmanning.k3s
