- hosts: aerohive
  name: show interfaces
  gather_facts: false
  tasks:
  - name: Configure users
    ansible.builtin.expect:
      command: "ssh -o StrictHostKeyChecking=no admin@{{ inventory_hostname }}"
      responses:
        (?i)password*:
          - "{{ cli_password }}"
        (.*)#: "{{ users_config }}"
    no_log: false