- hosts: tlsg2428p
  gather_facts: false
  name: Configure HAProxy Loadbalancer for external k8s cluster
  vars:
    ansible_network_os: vyos.vyos.vyos # Not actually a juniper device
    ansible_connection: network_cli
    interface: "1/0/24"
    state: enable
  tasks:

  - name: run config mode command and handle prompt/answer
    ansible.netcommon.cli_command:
      command: "{{ item }}"
      prompt:
        - Exit with uncommitted changes
      answer: y
    loop:
      - enable
      - configure
      - "interface gigabitEthernet {{ interface }}"
      - "power inline supply {{ state }}"
      - exit
      - exit
      - exit
    register: result

  - name: debug
    ansible.builtin.debug:
      var: result