---
all:
  children:
    molecule:
      hosts:
        fedora-desktop-test:
          mp:
            kubevirt:
              boot_source:
                type: data_volume_url
                url: resolved-by-create
                size: 50Gi
                storage_class: "{{ molecule_storage_class }}"
                volume_mode: Block
                access_modes:
                  - ReadWriteOnce
