---
- name: Apply baseline
  ansible.builtin.import_playbook: ../../playbooks/linux/baseline.yaml
- name: Apply install packages
  ansible.builtin.import_playbook: ../../playbooks/linux/install_packages.yaml
- name: Apply ssh authorized keys
  ansible.builtin.import_playbook: ../../playbooks/linux/ssh_authorized_keys.yaml
