---
all:
  children:
    molecule:
      hosts:
        ghapp-devenv:
          mp:
            kubevirt:
              boot_source: "{{ molecule_boot_sources.stream10 }}"
              ssh_user: cloud-user
              cpu:
                cores: 2
              memory: 4Gi
              vm_overrides:
                spec:
                  template:
                    spec:
                      architecture: amd64
                      domain:
                        machine:
                          type: pc-q35-rhel9.6.0
        ghapp-hermes:
          mp:
            kubevirt:
              boot_source: "{{ molecule_boot_sources.stream10 }}"
              ssh_user: cloud-user
              cpu:
                cores: 2
              memory: 4Gi
              vm_overrides:
                spec:
                  template:
                    spec:
                      architecture: amd64
                      domain:
                        machine:
                          type: pc-q35-rhel9.6.0
