---
all:
  children:
    molecule:
      hosts:
        imageclone:
          mp:
            kubevirt:
              boot_source:
                type: data_volume_source_ref
                source_ref:
                  name: "{{ molecule_image_name }}"
                  namespace: "{{ molecule_namespace }}"
                size: 50Gi
              admin_user: Administrator
              preference: windows.2k25
              sysprep_secret: "{{ inventory_hostname }}-sysprep-{{ molecule_consumer_run_id }}"
    windows:
      hosts:
        imageclone: {}
    windows_guests:
      hosts:
        imageclone: {}
