---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest'
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--ignore-certs --upgrade -f --no-cache --force-with-deps'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
#  python: requirements.txt

# does not work
additional_build_steps:
  append:
    - RUN wget https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    - RUN ./get_helm.sh
