---
all:
  children:
    molecule:
      hosts:
        restore-stream10:
          mp:
            kubevirt: "{{ molecule_guest_profiles.stream10 | combine(dict(ssh_user='igou', memory='4Gi')) }}"
    devenv:
      hosts:
        restore-stream10: {}
