---
- name: Clone a git repo example
  hosts: localhost
  vars:
    ansible_ssh_common_args: "-A"
  tasks:

    - name: Print a message
      ansible.builtin.git:
        repo: git@github.com:igou-io/igou-kubernetes.git
        dest: ~
        version: main

    - name: Ls the directory
      ansible.builtin.command: "ls ~/igou-kubernetes"
      changed_when: false
