---
- name: Controller node memory test
  hosts: "{{ hosts | default('all') }}"
  gather_facts: true
  vars:
    accumulator: "{{ ansible_facts }}"

  tasks:
    - name: Create accumulating facts
      ansible.builtin.set_fact:
        "{{ 'fact_' ~ item }}": "{{ accumulator }}"
        accumulator: >-
          {{
          accumulator
          | combine({ ('fact_' ~ item): accumulator })
          }}
      loop: "{{ range(1, 11) | list }}"
      loop_control:
        label: "{{ item }}"

    - name: Display fact_10 length
      ansible.builtin.debug:
        msg: "{{ fact_10 | length }}"
