---
version: 3
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
additional_build_files:
    - src: ansible.cfg
      dest: configs
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  python_interpreter:
    package_system: python3.12
    python_path: /usr/bin/python3.12
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - python3-jinja2 [platform:rpm]
    - which [platform:rpm]
    - git-core [platform:rpm]
    - git [platform:rpm]
    - libcurl-devel [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.12-devel [platform:rpm]
    - openssl-devel [platform:rpm]
    - libxml2-devel [platform:rpm]
    - libxslt-devel [platform:rpm]
    - 1password-cli [platform:rpm]
    - terraform [platform:rpm]
  python:
    - pytz  # for schedule_rrule lookup plugin
    - python-dateutil>=2.7.0  # schedule_rrule
    - awxkit  # For import and export modules
    - systemd-python
    - boto3
    - botocore
  galaxy:
    collections:
      - name: ansible.windows
      - name: community.windows
      - name: ansible.posix
      - name: ansible.netcommon
      - name: ansible.utils
      - name: community.crypto
      - name: community.general
      - name: redhat.satellite
      - name: redhat.insights
      - name: containers.podman
      - name: community.postgresql
      - name: infra.ah_configuration
      - name: redhat.rhel_system_roles
      - name: ansible.platform
      - name: ansible.hub
      - name: ansible.eda
      - name: ansible.controller
      - name: infra.aap_configuration
      - name: infra.aap_utilities
additional_build_steps:
  prepend_base: |
    RUN microdnf install -y git-core
  prepend_builder:
    - ENV PKGMGR_OPTS "--nodocs --setopt install_weak_deps=0 --enablerepo=rhocp-4.17-for-rhel-9-x86_64-rpms"
  prepend_final:
    - ENV PKGMGR_OPTS "--nodocs --setopt install_weak_deps=0 --enablerepo=rhocp-4.17-for-rhel-9-x86_64-rpms"
  append_base: |
    RUN $PYCMD -m pip install -U pip

    RUN echo "Target architecture is: $TARGETARCH"

    # Configure Terraform Repo
    RUN curl -o /etc/yum.repos.d/hashicorp.repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    RUN rpm --import https://downloads.1password.com/linux/keys/1password.asc && \
    sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'

  prepend_galaxy: |
    ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final: |
    RUN rm -f /etc/ansible/ansible.cfg
    RUN ansible-galaxy collection list