---
galaxy_info:
  author: David Igou
  description: Declaratively reconcile UniFi Network configuration
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: GenericLinux
dependencies: []
