---
# Generic Podman container destroy playbook
- name: Destroy Podman instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Destroy molecule instance(s)
      containers.podman.podman_container:
        name: "{{ item.name }}"
        state: absent
      register: server
      with_items: "{{ molecule_yml.platforms }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: podman_jobs
      until: podman_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    - name: Delete podman networks(s)
      containers.podman.podman_network:
        name: "{{ item }}"
        state: absent
      with_items: "{{ molecule_yml.platforms | selectattr('networks', 'defined')
                    | map(attribute='networks') | flatten | map(attribute='name') | unique }}"
      when: molecule_yml.platforms | selectattr('networks', 'defined') | list | length > 0
