---
# Generic Podman container destroy playbook
- name: Destroy Podman instances
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Destroy molecule instance(s)
      containers.podman.podman_container:
        name: "{{ item['name'] }}"
        state: absent
      register: server
      with_items: "{{ molecule_yml['platforms'] }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      ansible.builtin.async_status:
        jid: "{{ item['ansible_job_id'] }}"
      register: podman_jobs
      until: podman_jobs.finished
      retries: 300
      with_items: "{{ server['results'] }}"

    - name: Initialize podman network list
      ansible.builtin.set_fact:
        __podman_networks: []

    - name: Collect networks from platforms[].network
      ansible.builtin.set_fact:
        __podman_networks: "{{ __podman_networks + (item['network'] if (item['network'] is sequence and item['network'] is not string) else [item['network']]) }}"
      with_items: "{{ molecule_yml['platforms'] }}"
      when:
        - item['network'] is defined

    - name: Delete podman network(s)
      containers.podman.podman_network:
        name: "{{ item }}"
        state: absent
      with_items: "{{ __podman_networks | default([]) | unique }}"
      when:
        - __podman_networks | default([]) | length > 0
        - item not in ['bridge', 'none', 'host', 'slirp4netns']
        - item is not match('^ns:')
        - item is not match('^container:')