---
- name: Playbook to configure ansible controller post installation
  hosts: awx
  gather_facts: false
  tasks:
    - name: Configure AWX
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
      vars:
        assign_galaxy_credentials_to_org: false
        assign_default_ee_to_org: false