---
- hosts: localhost
  name: Configure awx
  gather_facts: false
  environment:
    CONTROLLER_HOST: "https://awx.apps.igou.systems"

  tasks:
  - name: Set platform level settings
    awx.awx.settings:
      settings:
        TOWER_URL_BASE: "https://awx.apps.igou.systems"
        ACTIVITY_STREAM_ENABLED_FOR_INVENTORY_SYNC: "true"
        AWX_ROLES_ENABLED: false
        AWX_COLLECTIONS_ENABLED: false

  - name: Create a new organization
    awx.awx.organization:
      name: "igou"
      description: "igou"
      state: present
      default_environment: igou-awx-ee
      notification_templates_started:
        - "slack"
      notification_templates_success:
        - "slack"
      notification_templates_error:
        - "slack"
      notification_templates_approvals:
        - "slack"

  # Create credentials manually
  # igou-inventory-git-token
  # aws-read-token
  # igou-ssh
  # igou-inventory-vault
  # igou-ssh-pass
  # armbian

  # Assume notification "slack" exists

  - name: Create igou-inventory project
    awx.awx.project:
      name: "igou-inventory"
      organization: "igou"
      state: present
      scm_url: https://github.com/igou-io/igou-inventory.git
      scm_type: git
      scm_clean: true
      scm_delete_on_update: true
      scm_update_on_launch: true
      scm_credential: igou-inventory-awx-github-pat
      update_project: true

  - name: Create igou-inventory inventory
    awx.awx.inventory:
      name: igou-inventory
      organization: "igou"
      state: present

  - name: Create igou-inventory git source
    awx.awx.inventory_source:
      name: igou-inventory-git-source
      inventory: igou-inventory
      source: scm
      source_project: igou-inventory
      verbosity: 2
      update_on_launch: false
      overwrite: true
      overwrite_vars: true

  - name: Update a igou-inventory-git-source
    awx.awx.inventory_source_update:
      name: "igou-inventory-git-source"
      inventory: "igou-inventory"
      organization: igou
      wait: true

  - name: Create igou-inventory aws source
    awx.awx.inventory_source:
      name: igou-inventory-aws-source
      inventory: igou-inventory
      source: ec2
      credential: aws-token
      verbosity: 2
      update_on_launch: false
      overwrite: true
      overwrite_vars: true
      source_vars:
        regions:
          - us-east-2
        keyed_groups:
          - prefix: private
            key: tags.role
        allow_duplicated_hosts: True
        hostnames:
          - private-ip-address

  - name: Update a igou-inventory-aws-source
    awx.awx.inventory_source_update:
      name: "igou-inventory-aws-source"
      inventory: "igou-inventory"
      organization: igou
      wait: true

  - name: Create igou-ansible project
    awx.awx.project:
      name: "igou-ansible"
      organization: "igou"
      state: present
      scm_url: https://github.com/igou-io/igou-ansible.git
      scm_type: git
      default_environment: igou-awx-ee
      update_project: true