---
- hosts: "{{ ansible_limit | default('all') }}"
  name: Update all systems
  become: "{{ become | default(true) }}"
  gather_facts: true
  roles:
    - role: robertdebock.update
      vars:
        update_autoremove: false
