---
- name: Update all systems
  hosts: "{{ ansible_limit | default('all') }}"
  become: "{{ become | default(true) }}"
  gather_facts: true
  roles:
    - role: robertdebock.update
      vars:
        update_autoremove: false
