---
- hosts: localhost
  name: Taint kuberenetes nodes
  gather_facts: false
  roles:
    - role: node_taint
      node_group: "{{ groups['camera'] }}"
      kube_taints:
        - effect: NoSchedule
          key: iot
          value: "true"

    - role: node_taint
      node_group: "{{ groups['climate'] }}"
      kube_taints:
        - effect: NoSchedule
          key: iot
          value: "true"
